# Generated by Django 5.1.3 on 2024-11-28 12:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authormodel',
            options={'verbose_name_plural': 'Autorzy'},
        ),
        migrations.AlterModelOptions(
            name='postmodel',
            options={'verbose_name_plural': 'Posty'},
        ),
        migrations.AlterModelOptions(
            name='tagmodel',
            options={'verbose_name_plural': 'Tagi'},
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='second_name',
            field=models.CharField(max_length=25, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.authormodel', verbose_name='Autor:'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Zawartość posta:'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Data:'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='tags',
            field=models.ManyToManyField(to='blog.tagmodel', verbose_name='Tag:'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Tytuł:'),
        ),
    ]
