# Generated by Django 5.1.3 on 2024-11-28 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_authormodel_options_alter_postmodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='content',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='ingredients',
            field=models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Składniki:'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='prepare',
            field=models.TextField(null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Sposób przygotowania:'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='excerpt',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator, django.core.validators.MaxLengthValidator(250)], verbose_name='skrót'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(upload_to='dishes'),
        ),
    ]
