# Generated by Django 5.1.3 on 2024-12-05 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_messagemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageModel',
        ),
    ]
